language: python
env:
  - WEB_PORT_80_TCP_ADDR=localhost
install:
  - sudo apt-get install -y liblua5.1-json nginx-extras
  - sudo cp nginx.conf /etc/nginx/nginx.conf
  - sudo cp *.lua /usr/share/nginx/

before_script:
  - pip install requests

script:
  - python tests/tests.py -v
